const fs = require('fs-extra');
const archiver = require('archiver');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const PLUGIN_SLUG = 'productbay';
// Go up one level from 'scripts' to root
const ROOT_DIR = path.join(__dirname, '..');
const BUILD_DIR = path.join(ROOT_DIR, 'dist');
const PLUGIN_DIR = path.join(BUILD_DIR, PLUGIN_SLUG);

// Read version from package.json
const packageJson = require(path.join(ROOT_DIR, 'package.json'));

// Default: slug-only for WordPress.org compatibility
// Use --versioned flag for GitHub releases or archival purposes
const includeVersion = process.argv.includes('--versioned');
const ZIP_NAME = includeVersion
	? `${PLUGIN_SLUG}-${packageJson.version}.zip`
	: `${PLUGIN_SLUG}.zip`;

// Files/Folders to COPY to the release
const INCLUDES = [
	'app',
	// 'assets' is handled separately with filtering (see copyAssetsFiltered)
	'languages',
	// 'vendor' is generated inside PLUGIN_DIR by composer install
	'productbay.php',
	'uninstall.php',
	'readme.txt',
	'composer.json',
];

/**
 * Files and patterns to EXCLUDE from the assets/ directory in production.
 *
 * - Source maps (*.map) — debug-only, ~1.7 MB total
 * - admin-rtl.css — auto-generated by @wordpress/scripts from the webpack-extracted
 *   CSS (js/admin.css, which is empty/2 bytes). The real styles come from Tailwind CLI
 *   in css/admin.css. This RTL file does NOT cover Tailwind styles, so it's useless.
 *   True RTL support would require generating RTL at the Tailwind CSS level.
 * - admin.css in js/ — 2-byte webpack artifact, not the real Tailwind CSS (css/admin.css)
 * - runtime.asset.php — auto-generated by @wordpress/scripts for the webpack runtime
 *   chunk, but never loaded by any PHP code (only admin.asset.php is used)
 */
const ASSETS_EXCLUDE_PATTERNS = [
	/\.map$/,
	/admin-rtl\.css$/,
	/^js[\\/]admin\.css$/,
	/runtime\.asset\.php$/,
];

/**
 * Copy the assets/ directory with filtering to exclude dev-only files.
 *
 * @param {string} srcDir  Source assets directory.
 * @param {string} destDir Destination assets directory.
 */
async function copyAssetsFiltered(srcDir, destDir) {
	await fs.copy(srcDir, destDir, {
		filter: (src) => {
			const rel = path.relative(srcDir, src);

			// Allow the root (srcDir itself)
			if (rel === '') {
				return true;
			}

			// Exclude files matching patterns
			if (!fs.statSync(src).isDirectory()) {
				return !ASSETS_EXCLUDE_PATTERNS.some((pattern) =>
					pattern.test(rel)
				);
			}

			return true;
		},
	});
}

/**
 * Strip `require-dev` and `config` sections from composer.json for production.
 * These are dev-only; `composer install --no-dev` already ignores them,
 * but shipping them adds unnecessary noise.
 *
 * @param {string} composerPath Path to the copied composer.json in PLUGIN_DIR.
 */
async function stripComposerDevSections(composerPath) {
	const composerData = await fs.readJson(composerPath);
	delete composerData['require-dev'];
	delete composerData.config;
	await fs.writeJson(composerPath, composerData, { spaces: '\t' });
}

(async () => {
	try {
		console.log('🚀 Starting Release Build with Bun...');

		// 1. Clean previous builds
		console.log('🧹 Cleaning old build...');
		await fs.remove(BUILD_DIR);
		await fs.remove(path.join(ROOT_DIR, ZIP_NAME));
		await fs.ensureDir(PLUGIN_DIR);

		// 2. Generate i18n files (POT + JSON translations)
		console.log('🌐 Generating i18n files...');
		execSync('bun run i18n:make-pot', { stdio: 'inherit', cwd: ROOT_DIR });
		execSync('bun run i18n:make-json', {
			stdio: 'inherit',
			cwd: ROOT_DIR,
		});

		// 3. Run Production Build (React + Tailwind)
		console.log('🛠  Building assets...');
		execSync('bun run build', { stdio: 'inherit', cwd: ROOT_DIR });

		// 4. Copy Files
		console.log('📂 Copying plugin files...');
		for (const item of INCLUDES) {
			const src = path.join(ROOT_DIR, item);
			const dest = path.join(PLUGIN_DIR, item);
			if (await fs.pathExists(src)) {
				await fs.copy(src, dest);
			}
		}

		// 5. Copy assets with filtering (exclude source maps, unused files)
		console.log('📂 Copying assets (filtered)...');
		await copyAssetsFiltered(
			path.join(ROOT_DIR, 'assets'),
			path.join(PLUGIN_DIR, 'assets')
		);

		// 6. Install Production Composer Dependencies (in the staging folder)
		// Run BEFORE stripping require-dev so composer.json matches the lock file
		console.log('📦 Installing Production Composer Dependencies...');
		await fs.copy(
			path.join(ROOT_DIR, 'composer.lock'),
			path.join(PLUGIN_DIR, 'composer.lock')
		);
		execSync('composer install --no-dev --optimize-autoloader', {
			stdio: 'inherit',
			cwd: PLUGIN_DIR,
		});

		// 7. Strip require-dev and config from composer.json (after install)
		console.log('📝 Cleaning composer.json for production...');
		await stripComposerDevSections(
			path.join(PLUGIN_DIR, 'composer.json')
		);

		// 8. Create Zip
		console.log('🤐 Zipping...');
		const output = fs.createWriteStream(path.join(ROOT_DIR, ZIP_NAME));
		const archive = archiver('zip', { zlib: { level: 9 } });

		output.on('close', () => {
			console.log(
				`✅ Success! Created ${ZIP_NAME} (${archive.pointer()} bytes)`
			);
		});

		archive.on('error', (err) => {
			throw err;
		});

		archive.pipe(output);
		// This puts the 'productbay' folder inside the zip (Standard WP requirement)
		archive.directory(BUILD_DIR, false);
		await archive.finalize();
	} catch (err) {
		console.error('❌ Error during build:', err);
		process.exit(1);
	}
})();
